services:
  - type: web
    name: fantrax-league-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fantrax-db
          property: connectionString

databases:
  - name: fantrax-db
    plan: free
    databaseName: fantrax_league_manager
    user: fantrax_user
