services:
  - type: web
    name: fantrax-league-manager
    runtime: python
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      mkdir -p /opt/render/project/src
      pip install -r requirements.txt
      python init_production_db.py
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PATH
        value: /opt/render/project/src/.venv/bin:$PATH
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///fantasy_league.db
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "false"
    python_version: "3.11.8"
