services:
  - type: web
    name: fantrax-league-manager
    runtime: python
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      export FLASK_APP=run.py
      flask db upgrade
      python init_production_db.py
      python -c "from app import create_app, db; from app.models import User; app = create_app(); app.app_context().push(); admin = User.query.filter_by(username='admin').first(); admin.set_password('admin123') if admin else None; db.session.commit()"
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
