services:
  - type: web
    name: fantrax-league-manager
    runtime: python
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install psycopg2-binary
      export FLASK_APP=run.py
      export FLASK_ENV=production
      flask db upgrade
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # This will preserve the value set in the dashboard
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
