services:
  - type: web
    name: fantrax-league-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.12"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
