"""Make gameweek_id optional in cup group matches

Revision ID: 0823f85b8d39
Revises: de6377b98cfa
Create Date: 2025-08-07 13:50:25.011174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0823f85b8d39'
down_revision = 'de6377b98cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cup_group_match', schema=None) as batch_op:
        batch_op.alter_column('gameweek_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cup_group_match', schema=None) as batch_op:
        batch_op.alter_column('gameweek_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
