"""add division_id to manager_of_the_month

Revision ID: 7d7aecc2e1f0
Revises: 0823f85b8d39
Create Date: 2025-08-07 18:14:43.463746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7aecc2e1f0'
down_revision = '0823f85b8d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_of_the_month', schema=None) as batch_op:
        # Add the column as nullable first
        batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_manager_of_the_month_division_id', 'division', ['division_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_of_the_month', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manager_of_the_month_division_id', type_='foreignkey')
        batch_op.drop_column('division_id')

    # ### end Alembic commands ###
