"""Add position column to TeamSeason

Revision ID: ada8ef3cb12e
Revises: efbd5466da3b
Create Date: 2025-05-22 10:56:32.123996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada8ef3cb12e'
down_revision = 'efbd5466da3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_season', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
