"""Add cup group stage models

Revision ID: de6377b98cfa
Revises: 8f1560d8bd57
Create Date: 2025-08-07 13:48:49.770988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6377b98cfa'
down_revision = '8f1560d8bd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cup_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['cup_competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cup_group_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Float(), nullable=True),
    sa.Column('away_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweek.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['cup_group.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cup_group_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cup_group.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cup_competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_groups', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('num_groups', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teams_per_group', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cup_competition', schema=None) as batch_op:
        batch_op.drop_column('teams_per_group')
        batch_op.drop_column('num_groups')
        batch_op.drop_column('has_groups')

    op.drop_table('cup_group_team')
    op.drop_table('cup_group_match')
    op.drop_table('cup_group')
    # ### end Alembic commands ###
